create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text not null,
  user_type text not null default 'colaborador',
  avatar text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint users_user_type_check
    check (user_type in ('colaborador', 'diretor', 'adm_supremo'))
);

create table if not exists public.demandas (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  categoria text not null,
  cliente text not null,
  descricao text not null,
  tempo integer not null,
  status text not null default 'Pendente',
  data timestamptz not null default timezone('utc', now()),
  constraint demandas_categoria_check
    check (
      categoria in (
        'Automação & IA',
        'Planejamento',
        'Criação & Design',
        'Suporte & Atendimento',
        'Tráfego Pago'
      )
    ),
  constraint demandas_tempo_check check (tempo >= 0)
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_demandas_user_id on public.demandas (user_id);
create index if not exists idx_demandas_data on public.demandas (data desc);
create index if not exists idx_sessions_user_id on public.sessions (user_id);
create unique index if not exists idx_sessions_token on public.sessions (token);
